# Copyright (c) 2017-2026 Onur Yaşar
# Licensed under AGPL v3 + Commercial Exception
# See LICENSE.txt

# https://github.com/rymory/rymory-core
# rymory.org 
# onuryasar.org
# onxorg@proton.me 

version: "3.9"
services:
  reverse-proxy:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
